# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

draw_ant <- function(canvas, directions, iterations, resolution) {
    .Call('_aRtsy_draw_ant', PACKAGE = 'aRtsy', canvas, directions, iterations, resolution)
}

iterate_chladni <- function(x, y, waves) {
    .Call('_aRtsy_iterate_chladni', PACKAGE = 'aRtsy', x, y, waves)
}

draw_circlemap <- function(canvas, left, right, bottom, top, iters) {
    .Call('_aRtsy_draw_circlemap', PACKAGE = 'aRtsy', canvas, left, right, bottom, top, iters)
}

get_collatz_sequence <- function(x) {
    .Call('_aRtsy_get_collatz_sequence', PACKAGE = 'aRtsy', x)
}

draw_collatz <- function(empty, series, even, odd) {
    .Call('_aRtsy_draw_collatz', PACKAGE = 'aRtsy', empty, series, even, odd)
}

iterate_flame <- function(canvas, iterations, resolution, edge, blend, weighted, post, final, extra, colors, functions, funcWeights, funcPars, variations, varWeights, varParams, postPars, finalPars, extraPars, bsym) {
    .Call('_aRtsy_iterate_flame', PACKAGE = 'aRtsy', canvas, iterations, resolution, edge, blend, weighted, post, final, extra, colors, functions, funcWeights, funcPars, variations, varWeights, varParams, postPars, finalPars, extraPars, bsym)
}

iterate_flow <- function(canvas, angles, lines, iters, ncolors, left, right, top, bottom, stepmax) {
    .Call('_aRtsy_iterate_flow', PACKAGE = 'aRtsy', canvas, angles, lines, iters, ncolors, left, right, top, bottom, stepmax)
}

iterate_maze <- function(X, x, y) {
    .Call('_aRtsy_iterate_maze', PACKAGE = 'aRtsy', X, x, y)
}

iterate_mesh <- function(canvas, points, centers, iterations, start, order, radii, increase) {
    .Call('_aRtsy_iterate_mesh', PACKAGE = 'aRtsy', canvas, points, centers, iterations, start, order, radii, increase)
}

get_closest_node <- function(attractor_x, attractor_y, nodes_x, nodes_y, attraction_distance) {
    .Call('_aRtsy_get_closest_node', PACKAGE = 'aRtsy', attractor_x, attractor_y, nodes_x, nodes_y, attraction_distance)
}

kill_attractors <- function(attractor_x, attractor_y, nodes_x, nodes_y, kill_distance) {
    .Call('_aRtsy_kill_attractors', PACKAGE = 'aRtsy', attractor_x, attractor_y, nodes_x, nodes_y, kill_distance)
}

draw_circle <- function(center_x, center_y, diameter, n) {
    .Call('_aRtsy_draw_circle', PACKAGE = 'aRtsy', center_x, center_y, diameter, n)
}

get_directions <- function(attractor_x, attractor_y, nodes_x, nodes_y, closest_nodes) {
    .Call('_aRtsy_get_directions', PACKAGE = 'aRtsy', attractor_x, attractor_y, nodes_x, nodes_y, closest_nodes)
}

iterate_phyllotaxis <- function(iter, a, p) {
    .Call('_aRtsy_iterate_phyllotaxis', PACKAGE = 'aRtsy', iter, a, p)
}

draw_planet <- function(canvas, resolution, radius, xcenter, ycenter, threshold, iterations, ncolors, colorsused, starprob, fade, lightright) {
    .Call('_aRtsy_draw_planet', PACKAGE = 'aRtsy', canvas, resolution, radius, xcenter, ycenter, threshold, iterations, ncolors, colorsused, starprob, fade, lightright)
}

draw_polylines <- function(X, ratio, iters, rows, cols) {
    .Call('_aRtsy_draw_polylines', PACKAGE = 'aRtsy', X, ratio, iters, rows, cols)
}

iterate_recaman <- function(n, start, increment) {
    .Call('_aRtsy_iterate_recaman', PACKAGE = 'aRtsy', n, start, increment)
}

draw_splits <- function(x, xend, y, yend, col, sda, ncols, iterations) {
    .Call('_aRtsy_draw_splits', PACKAGE = 'aRtsy', x, xend, y, yend, col, sda, ncols, iterations)
}

draw_squares <- function(X, neighbors, s, cuts, ratio) {
    .Call('_aRtsy_draw_squares', PACKAGE = 'aRtsy', X, neighbors, s, cuts, ratio)
}

draw_strokes <- function(canvas, neighbors, s, p) {
    .Call('_aRtsy_draw_strokes', PACKAGE = 'aRtsy', canvas, neighbors, s, p)
}

draw_turmite <- function(canvas, iters, row, col, p) {
    .Call('_aRtsy_draw_turmite', PACKAGE = 'aRtsy', canvas, iters, row, col, p)
}

deform <- function(x, y, s, maxdepth, resolution) {
    .Call('_aRtsy_deform', PACKAGE = 'aRtsy', x, y, s, maxdepth, resolution)
}

c_noise_knn <- function(x, y, z, newx, newy, k) {
    .Call('_aRtsy_c_noise_knn', PACKAGE = 'aRtsy', x, y, z, newx, newy, k)
}

